Cherry pick of 71e1dbf2568fd5582b4e1cfca2c3311caebc55b1 failed
stdout:
Auto-merging account_cashbox_l10n_latam_check/wizards/l10n_latam_payment_mass_transfer_views.xml
CONFLICT (content): Merge conflict in account_cashbox_l10n_latam_check/wizards/l10n_latam_payment_mass_transfer_views.xml
Auto-merging account_cashbox_l10n_latam_check/wizards/l10n_latam_payment_mass_transfer.py
Auto-merging account_cashbox/views/account_payment.xml
CONFLICT (content): Merge conflict in account_cashbox/views/account_payment.xml
Auto-merging account_cashbox/views/account_cashbox_session.xml
Auto-merging account_cashbox/views/account_cashbox.xml
CONFLICT (content): Merge conflict in account_cashbox/views/account_cashbox.xml
Auto-merging account_cashbox/models/account_cashbox_session.py
CONFLICT (content): Merge conflict in account_cashbox/models/account_cashbox_session.py
Auto-merging account_cashbox/models/account_cashbox.py

stderr:
14:44:37.709350 git.c:444               trace: built-in: git cherry-pick 71e1dbf2568fd5582b4e1cfca2c3311caebc55b1
error: could not apply 71e1dbf2... [IMP] Cashbox updates
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: