Cherry pick of 9c8932353b1e2651f1e6532118d5feaacb557a32 failed
stdout:
Auto-merging account_payment_group_financial_surcharge/views/account_move_views.xml
CONFLICT (content): Merge conflict in account_payment_group_financial_surcharge/views/account_move_views.xml
Auto-merging account_payment_group_financial_surcharge/__manifest__.py
CONFLICT (content): Merge conflict in account_payment_group_financial_surcharge/__manifest__.py

stderr:
22:22:03.874282 git.c:439               trace: built-in: git cherry-pick 9c8932353b1e2651f1e6532118d5feaacb557a32
error: could not apply 9c893235... [FIX] account_payment_group_financial_surcharge: Some fixes to solve issues.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

closes ingadhoc/account-payment#287

Signed-off-by: Nicolas Mac Rouillon <nmr@adhoc.com.ar>