Cherry pick of 093a5f5706f83f5032d45c83f7bf3eafa24d2b64 failed
stdout:
CONFLICT (modify/delete): account_payment_group/models/account_payment_group.py deleted in HEAD and modified in 093a5f57 ([FIX] _pay_group: adding the kanban view, for some reason, requires to add). Version 093a5f57 ([FIX] _pay_group: adding the kanban view, for some reason, requires to add) of account_payment_group/models/account_payment_group.py left in tree.

stderr:
01:07:06.836467 git.c:444               trace: built-in: git cherry-pick 093a5f5706f83f5032d45c83f7bf3eafa24d2b64
error: could not apply 093a5f57... [FIX] _pay_group: adding the kanban view, for some reason, requires to add
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: